<?php
/**
 * @file
 * Code for the OS Slideshow feature.
 */

include_once 'os_slideshow.features.inc';

/**
 * Implements hook_boxes_plugins().
 */
function os_slideshow_boxes_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'os_slideshow') . '/plugins';

  $info['os_slideshow_box'] = array(
    'title' => 'Slideshow',
    'description' => 'Slideshow',
    'tags' => array('Media'),
    'handler' => array(
      'class' => 'os_slideshow_box',
      'file' => 'os_slideshow_box.inc',
      'path' => $path,
      'parent' => 'os_boxes_default'
    )
  );

  return $info;
}

/**
 * Implelements hook_boxes_plugins_alter
 * 
 * Removes deprecated gallery slideshow from the new widgets list
 */
function os_slideshow_boxes_plugins_alter(&$plugins) {
  $plugins['os_boxes_slideshow']['factory'] = false;
}

/**
 * Implements hook_vsite_og_node_type_info().
 */
function os_slideshow_vsite_og_node_type_info() {
  return array('slideshow_slide' => 'group content');
}

/**
 * Implements hook_library().
 *
 * @author minorOffense <mwinstone@coldfrontlabs.ca>
 */
function os_slideshow_library() {
  $libraries['flexslider'] = array(
    'title' => 'FlexSlider',
    'website' => 'http://flex.madebymufffin.com/',
    'version' => '1.8',
    'js' => array(libraries_get_path('flexslider') . '/jquery.flexslider-min.js' => array(),),
    //'css' => array(libraries_get_path('flexslider') . '/flexslider.css' => array('type' => 'file','media' => 'screen')),
  );

  $libraries['responsiveslides'] = array(
    'title' => 'ResponsiveSlides.js',
    'website' => 'https://github.com/viljamis/ResponsiveSlides.js',
    'version' => '1.53',
    // Not original version. patched by HappyCog!
    'js' => array(libraries_get_path('responsiveslides') . '/responsiveslides.js' => array(),),
    //'css' => array(libraries_get_path('responsiveslides') . '/responsiveslides.css' => array('type' => 'file','media' => 'screen')),
  );
  return $libraries;
}

/**
 * Implements hook_form_FORMID_alter
 *
 * Attaches widget delta to form so it'll be available during node save
 */
function os_slideshow_form_slideshow_slide_node_form_alter(&$form, &$state, $form_id) {
  $form['field_image']['#suffix'] = t('Please use images larger than 980x330 pixels.');
  
  $widget = (isset($_GET['widget'])) ? $_GET['widget'] : @$state['input']['widget'];
  if (module_exists('spaces') && $space = spaces_get_space()) {
    $box = $space->controllers->boxes->get($widget);
  }
  else {
    $box = boxes_box_load($widget);
  }

  //$form['field_image']['und'][0]['#upload_validators']['imagefield_crop_upload_validate'][1]['widget']['settings']['resolution'] = '900x100';
  if ($widget) {
    $form['widget'] = array('#type' => 'hidden', '#value' => $widget);
  }

  // Remove sticky. Pull published out of vertical tab.
  $form['options']['sticky']['#type'] = 'hidden';
  // Only one item, so no need for the fieldset.
  unset($form['options']['#type']);
  unset($form['options']['#group']);

  // Hide additional settings except publishing options.
  foreach ($form as $name => &$item) {
    if (is_array($item) && isset($item['#group']) && ($item['#group'] == 'additional_settings')) {
      $item['#type'] = 'hidden';
    }
  }

  // Hide title. it will be automatically generated later.
  $form['title']['#type'] = 'hidden';
  $form['title']['#required'] = FALSE;
  
  // Remove preview, diff buttons.
  foreach (array('preview', 'preview_changes') as $action) {
    if (isset($form['actions'][$action])) {
      unset($form['actions'][$action]);
    }
  }
}

/**
 * Implements hook_imagefield_crop_instance_alter
 *
 * See: http://drupal.org/node/1915510#comment-7058848
 *
 * Changes the imagefield_crop widget to use our custom ratio.
 */
function os_slideshow_imagefield_crop_instance_alter(&$instance, $context) {
  if (isset($context['form']) && $context['form']['#id'] == 'slideshow-slide-node-form') {
    $widget = $context['form']['widget']['#value'];
  }
  elseif (isset($context['entity']) && isset($context['entity']->widget)) {
    $widget = $context['entity']->widget;
  }
  
  if (isset($widget) && $box = boxes_box_load($widget)) {
    $layout = $box->options['layout'];
    $layouts = _os_slideshow_layouts();
    $ratio = current($layouts[$layout]['ratio']);
    $content_sizes = _os_slideshow_region_size(NULL, 'content');
    $w = (is_array($content_sizes) && count($content_sizes)) ? current($content_sizes) : 1000;
    $h = intval(round($w/$ratio, 0));

    $instance['widget']['settings']['resolution'] = "${w}x${h}";
  }
}

/**
 * Implements hook_node_insert
 *
 * When a slideshow_slide is created, add its nid to the widget it was created for
 */
function os_slideshow_node_insert($node) {
  if ($node->type != 'slideshow_slide') {
    return;
  }

  if (isset($node->widget)) {
    if (module_exists('spaces') && $space = spaces_get_space()) {
      $box = $space->controllers->boxes->get($node->widget);
    }
    else {
      $box = boxes_box_load($node->widget);
    }

    // Array reduce's anon function gets the highest weight of all the slides,
    // so the newly inserted one can come last.
    $box->options['nodes'][(int)$node->nid] = array(
      'nid' => (int)$node->nid,
      'weight' => 1 + array_reduce($box->options['nodes'], create_function('$val, $next', 'return ($next["weight"]>$val) ? $next["weight"] : $val;'), 0),
	  );

    if ($space) {
      $space->controllers->boxes->set($box->delta, $box);
    }
    else {
      $box->save();
    }
  }
}

/**
 * Implements hook_node_presave
 *
 * Creates title since title was removed from form.
 */
function os_slideshow_node_presave($node) {
  if ($node->type == 'slideshow_slide') {
    
    $lang = $node->language;
    if (($file = file_load($node->field_image[$lang][0]['fid'])) == FALSE) {
      return;      
    } 

    // Set a default title.
    $node->title = isset($node->field_headline[$lang][0]) ? $node->field_headline[$lang][0]['value'] : $file->filename;
    
    // Add og_group_ref to attached slide.
    if (empty($file->og_group_ref)) {
      $file->og_group_ref = $node->og_group_ref;
      file_save($file);
    }
  }
}

/**
 * @function os_slideshow_process_form_nodes
 *
 * Form #process function.  After form is saved, remove the nids that were deleted.
 */
function os_slideshow_process_form_nodes($element, &$state, &$form) {
  // Bail out while the form is being built.
  if (empty($state['input'])) {
    return $element;
  }

  // Only keep nodes that have been returned from the form.
  $nodes_left = (isset($state['input']['nodes'])) ? array_keys($state['input']['nodes']) : array();
  foreach($form['options']['nodes_list']['#value'] as $nid) {
    if (!in_array($nid, $nodes_left)) {
      unset($element[$nid]);
    }
  }

  return $element;
}


/**
 * Implements hook_module_implements_alter
 *
 * Move our form alter to after url alias's so we can remove that form element.
 */
function os_slideshow_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['os_slideshow'])) {
    unset($implementations['os_slideshow']);
    $implementations['os_slideshow'] = false;
  }
}

/**
 * Implements hook_image_default_styles().
 *
 * Provides styles for each of our cropping ratios.
 */
function os_slideshow_image_default_styles() {
  $styles = array();

  $default_effects = array(
    'label' => 'Scale and crop',
    'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
    'effect callback' => 'image_scale_and_crop_effect',
    'dimensions callback' => 'image_resize_dimensions',
    'form callback' => 'image_resize_form',
    'summary theme' => 'image_resize_summary',
    'module' => 'image',
    'name' => 'image_scale_and_crop',
    'data' => array(),
    'weight' => '1',
  );

  // Make a preset for each aspect ratio using each of the widths available.
  $widths = _os_slideshow_region_size(NULL, 'content');
  foreach (_os_slideshow_image_aspect_ratios() as $label => $ratio) {
    foreach ($widths as $w) {
      $name = 'os_slideshow_' . $label . '_' . $w;
      $effects = $default_effects;
      $effects['data']['width'] = $w;
      $effects['data']['height'] = intval(round($w/$ratio, 0));

      $styles[$name] = array(
        'name' => $name,
        'effects' => array($effects),
      );
    }
  }

  return $styles;
}

/**
 * Implements hook_theme(),
 */
function os_slideshow_theme($existing, $type, $theme, $path) {
  return array(
    'os_slideshow_slideshow' => array(
      'template' => 'os_slideshow_slideshow',
      'variables' => array(
        'nodes' => array(),
        'slides' => NULL,
        'controls' => NULL,
        'timeout' => 4000,
        'speed' => 700,
        'effect' => 'fade',
        'layout' => NULL,
        'random' => FALSE,
      ),
    ),
    'os_slideshow_slide' => array(
      'template' => 'os_slideshow_slide',
      'variables' => array(
        'node' => NULL,
        'headline' => NULL,
        'description' => NULL,
        'image' => NULL,
        'style_name' => 'slideshow_980',
        'box_delta' => NULL,
      )
    ),
    'os_slideshow_controls' => array(
      'template' => 'os_slideshow_controls',
      'variables' => array('node_count' => 0),
    ),
  );
}

/**
 * Implements hook_preprocess_hook
 */
function os_slideshow_preprocess_os_slideshow_slide(&$vars) {
  $node = &$vars['node'];
  $lang = $node->language;
  $vars['headline'] = ($node->field_headline) ? $node->field_headline[$lang][0]['value'] : '';
  $vars['description'] = ($node->field_description) ? $node->field_description[$lang][0]['value'] : '';

  $img = ($node->field_image) ? $node->field_image[$lang][0]['uri'] : '';
  $img_vars = array('path' => $img, 'style_name' => $vars['style_name']);
  $img_vars['alt'] = (count($node->field_image[$lang][0]['field_file_image_alt_text'])) ? $node->field_image[$lang][0]['field_file_image_alt_text'][$lang][0]['safe_value'] : $node->field_image[$lang][0]['filename'];

  $vars['image'] = theme('image_style', $img_vars);
  $url = ($node->field_link) ? $node->field_link[$lang][0]['url'] : '';
  if ($url) {
    foreach (array('headline', 'description', 'image') as $elem) {
      $vars[$elem] = l($vars[$elem], $url, array('html'=>TRUE));
    }
  }
}

/**
 * Implements hook_preprocess_hook().
 */
function os_slideshow_preprocess_os_slideshow_slideshow(&$vars) {
  // Load javascript, pass it our settings.
  drupal_add_library('os_slideshow', 'responsiveslides');
  drupal_add_js(drupal_get_path('module', 'os_slideshow') . '/os_slideshow_slider.js');
  $settings = array('os_slideshow' =>   //http://www.woothemes.com/flexslider/
    array('boxes-box-'.$vars['box_delta'] => array(
      'pager' => TRUE,
      'nav' => TRUE,
      // Flex starts the timer after transition. Responsive starts it during.
      // Adding them will let responsive look like flex did.
      'timeout' => intval($vars['timeout'] + $vars['speed']),
      'speed' => $vars['speed'],  
      'random' => $vars['random'],
    ),
  ));
  // slideshowSpeed, animationSpeed, randomize, animation (fade or slide
  // (horizontal or vertical)).
  drupal_add_js($settings, 'setting');
  _os_slideshow_add_css();

  // Prepare images.
  $nodes = $vars['nodes'];
  foreach ($nodes as $nid => $node) {
    $nodes[$nid]['#weight'] = $node['weight'];
  }
  uasort($nodes, 'element_sort');

  // Get slides - image with descriptionץ
  $nodes = node_load_multiple(array_keys($nodes));
  $vars['slides'] = array();
  $slide_vars = array('style_name' => _os_slideshow_get_style_name($vars['layout'], $vars['box_delta']));
  foreach ($nodes as $nid => $node) {
    if ($node->status) {
      $slide_vars['node'] = $node;
      $vars['slides'][] = theme('os_slideshow_slide', $slide_vars);
    }
    else {
      // Controls should only know about published images so remove the
      // unpublished ones
      unset($nodes[$nid]);
    }
  }

  // Get controls.
  $control_vars = array('node_count' => count($nodes));
  $vars['controls'] = theme('os_slideshow_controls', $control_vars);
}

/**
 * @function _os_slideshow_get_animation_direction
 *
 * Flexslider has a transition effect with a direction argument.  This splits them or sets the arg to null
 */
function _os_slideshow_get_animation_direction($effect) {
  $effects = explode('-', $effect);
  return (count($effects)>1) ? $effects : array($effect, NULL);
}

/**
 * @function _os_slideshow_get_style_name()
 *
 * Gets a style for the aspect ratio and region currently being used.
 */
function _os_slideshow_get_style_name($layout, $delta) {
  $layouts = _os_slideshow_layouts();
  if (!isset($layouts[$layout])) {
    $layout = current(array_keys($layouts));
  }
  $aspect_ratio = current(array_keys($layouts[$layout]['ratio']));

  // Figure out what region the slideshow is in and what other regions are
  // active so we can determine how wide the slideshow can be.
  $context_blocks = &drupal_static('context_reaction_block_list');
  $region = 'content_top';
  if(!$context_blocks){
    // Populate $context_blocks.
    $plugin = context_get_plugin('reaction', 'block');
    $plugin->block_list($region);
  }

  foreach ($context_blocks as $reg => $blocks){
    if(isset($blocks['boxes-'.$delta])){
      $region = $reg;
      break;
    }
  }

  // Get valid image styles for this aspect ratio.
  $sizes = array();
  foreach (os_slideshow_image_default_styles() as $style) {
    if (strpos($style['name'], 'os_slideshow_'.$aspect_ratio) === 0) {
      $sizes[$style['effects'][0]['data']['width']] = $style['name'];
    }
  }

  // Select the smallest style that's bigger than the current region.
  ksort($sizes);
  $size = _os_slideshow_region_size($region);
  foreach ($sizes as $width => $name) {
    if ($width >= $size) {
      break;
    }
  }

  return $name;
}

/**
 * @function _os_slideshow_region_size
 *
 * Returns the max width of a region given the list of regions that are in use.
 *
 * If $get_row_widths is provided, calculate and return the widths for that row of regions.
 */
function _os_slideshow_region_size($region, $get_row_widths = '') {
  $full_width = 980;

  $rows = array(
    'content' => array(
      // This region.
      'main' => 'content_top',
      // Its sidebars.
      'sides' =>  array('sidebar_first', 'sidebar_second'),
      // Widest sidebar when one sidebar is shown.
      'solo_side_width' => 300,
      // Widest sidebar when both are shown.
      'pair_side_width' => 250,
      // Thinnest possible sidebar.
      'min_side' => 160,
    ),
    'headers' => array(
      'main' => 'header_second',
      'sides' => array('header_first', 'header_third'),
      'solo_side_width' => 300,
      'pair_side_width' => 250,
      'min_side' => 160,
    ),
    'footers' => array(
      'main' => 'footer',
      'sides' => array('footer_first', 'footer_third'),
      'solo_side_width' => .25 * $full_width,
      'pair_side_width' => .25 * $full_width,
      'min_side' => .25 * $full_width,
    )
  );

  // Page content has extra regions.
  $rows['content_bottom'] = $rows['content'];
  $rows['content_bottom']['main'] = 'content_bottom';

  $rows['content_second'] = $rows['content'];
  $rows['content_second']['main'] = 'content_second';
  
  $rows['content_first'] = $rows['content'];
  $rows['content_first']['main'] = 'content_first';
  
  // Default behavior.
  if (!$get_row_widths) {
    $plugin = context_get_plugin('reaction', 'block');
    foreach($rows as $row) {
      if ($region != $row['main'] && !in_array($region, $row['sides'])) { 
        continue;
      }

      // Count the number of active regions.
      $sides_count = 0;
      foreach ($row['sides'] as $side){
        if (count($plugin->block_list($side))) {
          $sides_count++;
        }
      }

      if ($region == $row['main']) {
        $widths = array($full_width, $full_width - $row['min_side'], $full_width - 2*$row['min_side']);
        return $widths[$sides_count];
      } elseif (in_array($region, $row['sides'])) {
        return ($sides_count > 1) ? $row['pair_side_width'] : $row['solo_side_width'];
      }
    }

    //just assume full and let the browser resize.
    return $full_width;
  }

  // Or describe the possible widths of one of the rows.
  if (isset($rows[$get_row_widths])) {
    $row = $rows[$get_row_widths];
    return array(
      $full_width,
      $full_width - $row['min_side'],
      $full_width - 2*$row['min_side'],
      $row['solo_side_width']
    );
  }

  return FALSE;
}

/**
 * @function _os_slideshow_image_aspect_ratios
 *
 * Defines the aspect ratios supported by this module.
 */
function _os_slideshow_image_aspect_ratios() {
  return array(
    '3:1' => 3/1,
    '16:9' => 16/9,
  );
}

/**
 * @function _os_slideshow_layouts
 *
 * List the available layouts and their ratios.
 */
function _os_slideshow_layouts() {
  return array(
    '3_1_overlay'  => array('ratio' => array('3:1' => 3/1), 'name' => 'Widescreen Overlay'),
    '16_9_overlay' => array('ratio' => array('16:9' => 16/9), 'name' => 'Standard Overlay'),
    '16_9_below'   => array('ratio' => array('16:9' => 16/9), 'name' => 'Standard Below'),
    '16_9_side'    => array('ratio' => array('16:9' => 16/9), 'name' => 'Standard Side'),
 );
}


/**
 * @function _os_slideshow_add_css()
 *
 * Adds this module's css or slideshow css from one of our themes
 */
function _os_slideshow_add_css() {
  ctools_include('themes', 'os');
  $theme = os_get_themes(os_theme_get());
  if ($file = @$theme->info['os']['os_slideshow']) {
    drupal_add_css(drupal_get_path('theme', $theme->name)) . $file;
  }
  else {
    drupal_add_css(drupal_get_path('module', 'os_slideshow') . '/os_slideshow.css');
  }
}
