<?php

/**
 * @file cp_appearance.module
 *
 * Provides and handles form for cp/appearance
 */

use GitWrapper\GitWrapper;
use GitWrapper\GitException;

/**
 * Implements hook_menu().
 */
function cp_appearance_menu(){
  $items = array();
  $items['cp/appearance'] = array(
    'title' => 'Appearance',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'cp_appearance_theme_picker_form'
    ),
    'weight' => 20,
    'menu_name' => 'cp',
    'access callback' => array(
      'spaces_access_admin'
    )
  );

  $items['cp/appearance/theme'] = array(
    'title' => t('Theme'),
    'page callback' => 'drupal_get_form',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'page arguments' => array(
      'cp_appearance_theme_picker_form'
    ),
    'weight' => 20,
    'menu_name' => 'cp',
    'access callback' => array(
      'spaces_access_admin'
    )
  );

  $items['cp/appearance/add-subtheme'] = array(
    'title' => 'Add subtheme',
    'page callback' => 'cp_appearance_select_method',
    'access callback' => 'cp_appearance_sub_theme_access',
    'type' => MENU_LOCAL_ACTION,
  );

  foreach (subtheme_types() as $key => $info) {
    // Check if there is an override function of the base form.
    $form_id = function_exists('cp_appearance_manage_' . $key) ? 'cp_appearance_manage_' . $key : 'cp_appearance_manage_base';

    $items['cp/appearance/add-subtheme/' . $key] = array(
      'title' => $info->name,
      'page callback' => 'drupal_get_form',
      'page arguments' => array($form_id, 3),
      'access callback' => 'cp_appearance_sub_theme_access',
    );
  }

  return $items;
}

/**
 * Access callback.
 */
function cp_appearance_sub_theme_access() {
  if (module_exists('vsite') && $vsite = vsite_get_vsite()) {
    return og_user_access('node', $vsite->group->nid, 'manage subtheme', NULL, FALSE, TRUE);
  }
}

/**
 * Implements hook_theme().
 */
function cp_appearance_theme() {
  $theme = array();

  $theme['cp-appearance-theme-item'] = array(
    'variables' => array(
      'info' => array(),
      'sub_theme' => ''
    ),
    'template' => 'cp-appearance-theme-item',
    'path' => drupal_get_path('module', 'cp_appearance') . '/theme'
  );

  $theme['cp_appearance_theme_picker_form'] = array(
    'render element' => 'form',
    'function' => 'theme_cp_appearance_theme_picker_form'
  );

  $theme['cp_appearance_add_subtheme_list'] = array();

  return $theme;
}

/**
 * Form builder for CP > Appearance page.
 */
function cp_appearance_theme_picker_form($form, &$form_state) {
  // Instantiates the form array and assets.
  $module_path = drupal_get_path('module', 'cp_appearance');
  $form = array(
    '#title' => t('Theme Picker'),
    '#theme' => array(
      'cp_appearance_theme_picker_form'
    ),
    '#validate' => array(
      'cp_appearance_theme_picker_form_validate'
    ),
    '#attached' => array(
      'js' => array("{$module_path}/theme/cp_appearance_theme_picker.js"),
      'css' => array("{$module_path}/theme/cp-appearance-theme_picker.css"),
    )
  );

  ctools_include('themes', 'os');
  $themes = os_get_themes();
  ksort($themes);
  $radio_options = array();
  $default_flavor = '';

  // Adds each theme option to the form, and flavor options if available.
  foreach ($themes as $theme) {
    // Adds this theme to the radio options.
    $info = $theme->info;
    $info['theme_name'] = $theme->name;
    $radio_options[$info['theme_name']] = $info['theme_name'];

    // Only continues if this theme has flavors.
    $theme_flavors = os_theme_get_flavors($info['theme_name']);
    $flavor_options = _cp_appearance_get_flavor_options($theme_flavors, $info, $default_flavor);
    if (!count($flavor_options)) {
      continue;
    }

    // Adds the flavor select option to the form.
    $flavor_key = 'os_appearance_' . $info['theme_name'] . '_flavor';
    $form[$flavor_key] = array(
      '#type' => 'select',
      '#title' => t('Flavor'),
      '#options' => $flavor_options,
      '#default_value' => variable_get($flavor_key, $default_flavor),
      '#ajax' => array(
        'callback' => 'cp_appearance_swap_screenshot',
        'wrapper' => 'screenshot_' . $theme->name
      )
    );
  }

  // Sorts featured themes to the front.
  $featured_themes = array_filter(variable_get('cp_appearance_featured_themes', array()));
  $current_theme = os_theme_get();
  if (count($featured_themes)) {
    $first_themes = array();
    $other_themes = $themes;
    foreach ($other_themes as $theme_name => $theme) {
      if (in_array($theme_name, $featured_themes)) {
        $first_themes[$theme_name] = $theme;
        unset($other_themes[$theme_name]);
      }
    }
  }

  // Moves default theme to the front of the array.
  if (count($first_themes)) {
    if (isset($first_themes[$current_theme])) {
      $current_theme = _cp_appearance_move_option_to_front($first_themes, $current_theme);
    }
    elseif (isset($other_themes[$current_theme])) {
      $current_theme = _cp_appearance_move_option_to_front($other_themes, $current_theme);
    }
    $featured_header =  array('HEADER_FEATURED' => 'HEADER_FEATURED');
    $other_header = array('HEADER_OTHER' => 'HEADER_OTHER');
    $themes = array_merge($featured_header, $first_themes, $other_header, $other_themes);
  }
  elseif (isset($themes[$current_theme])) {
    $current_theme = _cp_appearance_move_option_to_front($themes, $current_theme);
  }
  // Selects the first option in case the current theme wasn't found.
  else {
    $current_theme = key($themes);
  }

  // Adds the theme options to form
  $form['theme_default'] = array(
    '#enabled_themes' => $themes,
    '#type' => 'radios',
    '#options' => $radio_options,
    '#default_value' => $current_theme,
    '#tree' => TRUE,
  );

  $form = system_settings_form($form);

  return $form;
}

/**
 * Helper function for theme picker form.
 */
function _cp_appearance_move_option_to_front(&$options, $key) {
  if (empty($options)) {
    return FALSE;
  }
  if (isset($options[$key])) {
    $value = $options[$key];
    unset($options[$key]);
    $first_option = array($key => $value);
    $options = array_merge($first_option, $options);
  }
  else {
    $key = key($options);
  }

  return $key;
}

/**
 * Remove variables that do not need to be saved in the DB for all the unused theme-flavors
 *
 * @param $form
 * @param $form_state
 */
function cp_appearance_theme_picker_form_validate($form, &$form_state){
  $op = isset($form_state['values']['op']) ? $form_state['values']['op'] : '';

  if ($op == t('Reset to defaults')) {
    return;
  }

  $theme_default = $form_state['values']['theme_default'];
  foreach ( $form_state['values'] as $key => $value ) {
    //No need to save all the default flavor variables
    if ($key != "os_appearance_" . $theme_default . "_flavor" && substr($key, 0, 14) == "os_appearance_" && substr($key, - 7) == "_flavor") {
      unset($form_state['values'][$key]);
    }
  }
}

/**
 * Processes all the flavors a theme has.
 *
 * @param array $theme_flavors
 *  	List of flavors used by this theme
 * @param array $info
 *  	Theme info
 * @param &string $default_flavor
 * 		Flavor to default to
 *
 * @return array
 */
function _cp_appearance_get_flavor_options($theme_flavors, $info, &$default_flavor){
  $options = array();
  if (count($theme_flavors)) {
    $options = array(
      'default' => (isset($info['flavor_name'])) ? $info['flavor_name'] : t('Default ')
    );
    $options['default'] .= t(' (Default)');

    foreach ( $theme_flavors as $key => $flavor ) {
      if (isset($flavor['flavor_name'])) {
        $options[$key] = $flavor['flavor_name'];
        $default_flavor = $key;
      }
      else {
        $options[$key] = $flavor['name'];
      }
    }
  }

  return $options;
}

/**
 * Renders the theme_picker form.
 */
function theme_cp_appearance_theme_picker_form($variables) {
  $form = $variables['form'];

  // Builds each item containing a screenshot-option or section separators.
  $items = array();
  foreach ($form['theme_default']['#enabled_themes'] as $theme) {
    if (in_array($theme, array('HEADER_FEATURED', 'HEADER_OTHER'))) {
      $items[] = _cp_appearance_theme_header_item($theme);
    }
    else {
      $items[] = _cp_appearance_theme_screenshot_item($theme, $form);
    }
  }

  // Builds the "Theme picker" list of tile screenshots.
  $form['theme_picker'] = array(
    '#theme' => 'item_list',
    '#items' => $items,
    '#title' => NULL,
    '#attributes' => array('class' => 'theme-picker'),
  );

  // Moves the actions button group to the bottom of the form.
  $actions = $form['actions'];
  unset($form['actions']);
  $form['actions'] = $actions;

  // Removes this theme wrapper and renders the the form.
  unset($form['#theme']);
  $output = drupal_render($form);

  return $output;
}

/**
 * Returns a list item build array to inject into the options list as separator.
 *
 * @param string $header_type
 *   One of 'HEADER_FEATURED' or 'HEADER_OTHER'.
 *   If featured, prepares the value of 2 configurable settings to display,
 *   otherwise prepares an item with the text "Other themes".
 *
 * @return array $build
 *   An associative array to be sent to theme_list as a $items element.
 */
function _cp_appearance_theme_header_item($header_type) {
  $build = array();
  $build['class'] = array('false-item');
  $build['id'] = 'theme-' . str_replace('_', '-', strtolower($header_type));
  $title = $subtitle = '';

  switch ($header_type) {
    case 'HEADER_FEATURED':
      $default = t('Featured themes');
      $display_title = variable_get('cp_appearance_featured_display_title', $default);
      if (!empty($display_title)) {
        $title = '<h2>' . check_plain($display_title) . '</h2>';
      }
      $description = variable_get('cp_appearance_featured_description', '');
      if (!empty($description)) {
        $subtitle = '<p>' . check_plain($description) . '</p>';
      }
      break;

    case 'HEADER_OTHER':
      $title = '<h2>' . t('Other themes') . '</h2>';
      break;
  }

  $build['data'] = $title . $subtitle;

  return $build;
}

/**
 * Prepares a single theme's screenshot & select list for the theme picker form.
 *
 * @param object $theme
 *   An individual available theme.
 * @param array $form
 *   The form object for the entire CP > Appearance page.
 *
 * @return array $item
 *   A Drupal render array to be sent to theme_item_list().
 */
function _cp_appearance_theme_screenshot_item($theme, &$form) {
  $subtheme_select_list = '';
  $info = array_merge((array) $theme->info, array(
    'theme_name' => $theme->name
  ));

  // Prepares each theme's subtheme select list and screenshot URL.
  $key = 'os_appearance_' . $theme->name . '_flavor';
  if (array_key_exists($key, $form)) {
    $subtheme_select_list = drupal_render($form[$key]);
    if ($flavor = $form[$key]['#default_value']) {
      $flavors = os_theme_get_flavors();
      if (array_key_exists($flavor, $flavors) && array_key_exists('screenshot', $flavors[$flavor]) && $flavors[$flavor]['module'] == $theme->name) {
        $info['screenshot'] = $flavors[$flavor]['path'] . '/' . $flavors[$flavor]['screenshot'];
      }
    }
    unset($form[$key]);
  }

  // Prepares the list item to be processed by our custom template.
  // @see cp-appearance-theme-item.tpl.php
  $status_class = '';
  if ($theme->name == $form['theme_default']['#default_value']) {
    $status_class = 'current';
  }
  $item = array(
    'class' => array(
      'item-theme-picker',
      $status_class,
    ),
    'id' => 'theme-' . str_replace('_', '-', $theme->name),
    'data' => theme('cp-appearance-theme-item', array(
      'info' => $info,
      'sub_theme' => $subtheme_select_list,
    ))
  );

  return $item;
}

/**
 * menu item takes a flavor and returns its screenshot via ajax
 */
function cp_appearance_swap_screenshot($form, &$state){
  ctools_include('themes', 'os');

  $trigger = $state['triggering_element']['#name'];
  $flavor = $state['values'][$trigger];

  $flavors = os_theme_get_flavors();
  if (array_key_exists($flavor, $flavors)) {
    $path = $flavors[$flavor]['path'] . '/' . $flavors[$flavor]['screenshot'];
    $module = $flavors[$flavor]['module'];
  }

  //no screenshot or flavor.  just use the default
  if (! ($path && file_exists($path))) {
    $module = str_replace('os_appearance_', '', $trigger);
    $module = str_replace('_flavor', '', $module);
    $theme = os_get_themes($module);
    $path = $theme->info['screenshot'];
  }

  return theme('image', array(
    'path' => $path,
    'alt' => t('Screenshot for %theme theme', array(
      '%theme' => $module
    )),
    'title' => '',
    'attributes' => array(
      'class' => 'screenshot',
      'id' => 'screenshot_' . $module
    ),
    'getsize' => FALSE
  ));
}


function cp_appearance_cp_settings() {
  $setting['enable_responsive'] = array(
    'group' => array(
      '#title' => t('Responsive'),
      '#id' => 'responsive',
    ),
    'form' => array(
      '#type' => 'checkbox',
      '#default_value' => variable_get('enable_responsive', false),
      '#title' => t('Enable responsive behaviors'),
      '#description' => t('Responsive behaviors will change the layout of your page to fit the screens of smaller devices, such
        as phones or tablets. Disabling this will prevent the layout from changing, but could make using your site more difficult
        on smaller devices.'),
    ),
  );

  return $setting;
}

/**
 * Implements hook_admin_paths().
 */
function cp_appearance_admin_paths() {
  return array(
    'cp/appearance/add-subtheme' => TRUE,
    'cp/appearance/add-subtheme/*' => TRUE,
  );
}

/**
 * Implements hook_og_permission().
 */
function cp_appearance_og_permission() {
  return array(
    'manage subtheme' => array(
      'title' => t('Add subtheme'),
      'description' => t('Allow the user to add subtheme.'),
    ),
  );
}

/**
 * Theme function - selecting the
 */
function theme_cp_appearance_add_subtheme_list($variables) {
  $types = $variables['types'];

  if ($types) {
    $output = '<h4>Download the <a target="_blank" href="https://github.com/openscholar/starterkit">Subtheme Starter Kit</a> to begin developing your custom theme.</h4>';
    $output .= '<ul class="admin-list">';
    foreach ($types as $type => $info) {
      $output .= '<li class="clearfix">';
      $output .= '<span class="label">' . l($info->name, 'cp/appearance/add-subtheme/' . $type) . '</span>';
      $output .= '<div class="description">' . filter_xss_admin($info->description) . '</div>';
      $output .= '</li>';
    }
    $output .= '</ul>';
  }
  else {
    $output = '<p>' . t('There are no subtheme types. Go to the <a href="@url">subtheme types create page</a> to add a new subtheme type.', array('@url' => url('admin/structure/subtheme'))) . '</p>';
  }

  return $output;
}

/**
 * List of subtheme types.
 */
function subtheme_types() {
  $types = array();

  $types['zip'] = (object)array(
    'name' => t('Zip'),
    'description' => t('Upload zip files.'),
  );

  $types['git'] = (object)array(
    'name' => t('Git'),
    'description' => t('Clone from a repository.'),
  );

  return $types;
}

/**
 * Select method for uploading the subtheme.
 */
function cp_appearance_select_method() {
  $types = subtheme_types();

  return theme('cp_appearance_add_subtheme_list', array(
    'types' => $types,
  ));
}

/**
 * Editing a basic sub theme.
 */
function cp_appearance_manage_base($form, &$form_state) {
  $form['file'] = array(
    '#title' => t('Themes'),
    '#type' => 'managed_file',
    '#description' => t('The uploaded image will be displayed on this page using the image style choosen below.'),
    '#required' => TRUE,
    '#upload_location' => 'public://',
    '#upload_validators' => array(
      'file_validate_extensions' => array('zip'),
    ),
    '#weight' => -99,
  );

  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Save'),
    ),
    'cancel' => array(
      '#type' => 'markup',
      '#markup' => l(t('Cancel'), 'cp/appearance/add-subtheme'),
    ),
  );

  return $form;
}

/**
 * Validate function - verify the subtheme based on a theme.
 */
function cp_appearance_manage_base_validate($form, $form_state) {
  $subtheme = new SubTheme($form_state['values']['file']);

  $subtheme->extract();
  $info = $subtheme->parseInfo();

  cp_appearance_validate_subtheme($info, 'file');
}

/**
 * Validate the subtheme before creating the subtheme entity.
 *
 * @param $info
 *  The parsed info file.
 * @param $form_element_name
 *  The form element.
 * @param bool $in_form
 *  Define if the validation is happening in a form. Used for set form errors.
 *  When validation is not happening in a form set to FALSE.
 *
 * @return bool
 *  Return true or false if the subtheme is validated or not.
 */
function cp_appearance_validate_subtheme($info, $form_element_name, $in_form = TRUE) {
  $themes = list_themes();

  if (empty($info['module'])) {
    if ($in_form) {
      form_set_error($form_element_name, t('The theme you uploaded is not valid.  `module` directive missing.'));
    }

    return FALSE;
  }
  else if (!in_array($info['module'], array_keys($themes))) {
    if ($in_form) {
      form_set_error($form_element_name, t('The theme you uploaded is not valid.  `module` refers to a theme that does not exist.'));
    }

    return FALSE;
  }

  return TRUE;
}

/**
 * Editing or creating a new sub theme.
 */
function cp_appearance_manage_base_submit($form, &$form_state) {
  $file = new Subtheme($form_state['values']['file']);

  $vsite = vsite_get_vsite();
  $flavors = $vsite->controllers->variable->get('flavors');

  // Parse the info.
  $info = $file->parseInfo();

  // Save the path of the extracted theme for later.
  $flavors[$info['theme name']] = array(
    'path' => $file->extractPath,
    'name' => $info['name'],
  );

  $vsite->controllers->variable->set('flavors', $flavors);

  $form_state['redirect'] = 'cp/appearance';
}

/**
 * Adding a theme - git.
 */
function cp_appearance_manage_git($form, &$form_state, $type) {
  // Adding the git library.
  require_once libraries_get_path('git') . '/autoload.php';

  // Get the name of the current vsite so we can create a library to clone into
  // the themes via GIT.
  $form['repository'] = array(
    '#type' => 'textfield',
    '#title' => t('Git repository address'),
    '#required' => TRUE,
    '#ajax' => array(
      'callback' => 'cp_appearance_git_method_get_ajax_branches',
      'wrapper' => 'branches-wrapper',
      'method' => 'replace',
      'keypress' => TRUE,
    ),
  );

  $branches = array();

  if ($repository_address = !empty($form_state['values']['repository']) ? $form_state['values']['repository'] : FALSE) {
    $wrapper = new GitWrapper();
    $wrapper->setPrivateKey('.');

    $path = variable_get('file_public_path', conf_path() . '/files') . '/subtheme/' . $repository_address;

    // @todo: Remove the github hardcoding.
    $path = str_replace(array('http://', 'https://', '.git', 'git@github.com:'), '', $path);

    if (!file_exists($path)) {
      drupal_mkdir($path, NULL, TRUE);
    }

    $git = $wrapper->workingCopy($path);

    if (!$git->isCloned()) {
      try {
        $git->clone($repository_address);
        $git->setCloned(TRUE);
      }
      catch (GitException $e) {
        // Can't clone the repo.
        drupal_set_message(t('Could not clone @repository, error @error', array('@repository' => $repository_address, '@error' => $e->getMessage(), 'warning')));
      }
    }

    $form['path'] = array(
      '#type' => 'value',
      '#value' => $path,
    );

    if ($git->isCloned()) {
      try {
        foreach ($git->getBranches()->remote() as $branch) {
          if (strpos($branch, ' -> ') !== FALSE) {
            // A branch named "origin/HEAD  -> xyz" is provided by the class, we
            // don't need it.
            continue;
          }
          $branches[str_replace(' ', '_', $branch)] = $branch;
        }
      }
      catch (GitException $e) {
      }
    }

    $subtheme = new SubTheme();
    $subtheme->path = $path;
    $form_state['subtheme'] = $subtheme;
  }

  $form['branches_wrapper'] = array(
    '#prefix' => '<div id="branches-wrapper">',
    '#suffix' => '</div>',
  );

  $valid_repo = FALSE;

  if ($branches) {
    $form['branches_wrapper']['branch'] = array(
      '#type' => 'select',
      '#title' => t('Branch'),
      '#description' => t('Enter the branch of the git repository'),
      '#options' => $branches,
      '#required' => TRUE,
    );

    $valid_repo = TRUE;
  }
  elseif (!$branches && $repository_address) {
    $form['branches_wrapper']['branch'] = array('#markup' => '<div id="branches">' .  t('Git repository is wrong.') . '</div>');
  }
  if ($valid_repo) {
    $form['branches_wrapper']['actions'] = array(
      '#type' => 'actions',
      'submit' => array(
        '#type' => 'submit',
        '#value' => t('Save'),
      ),
    );
  }
  else {
    // Place holder for Ajax.
    $form['branches_wrapper']['actions'] = array(
      '#type' => 'actions',
      'submit' => array(
        '#markup' => '<a href="#">' . t('Fetch branches') . '</a>',
      ),
    );
  }

  return $form;
}

/**
 * Return piece of the form for AJAX rendering.
 */
function cp_appearance_git_method_get_ajax_branches($form, $form_state) {
  return $form['branches_wrapper'];
}

/**
 * Validate handler - verify the user selected a branch.
 */
function cp_appearance_manage_git_validate($form, $form_state) {
  if (empty($form_state['values']['branch'])) {
    return;
  }

  require_once libraries_get_path('git') . '/autoload.php';

  $repository = $form_state['values']['repository'];
  $branch = $form_state['values']['branch'];

  $path = $form_state['values']['path'];

  $wrapper = new GitWrapper();
  $wrapper->setPrivateKey('.');
  $git = $wrapper->workingCopy($path);

  // We pull, in case the user wants to reload a subtheme.
  try {
    $git->checkout($branch, array('t' => TRUE));
  }
  catch (GitException $e) {
  }

  try {
    $git->pull();
  }
  catch (GitException $e) {
  }

  if (empty($form_state['subtheme'])) {
    return;
  }

  $subtheme = $form_state['subtheme'];

  $info = $subtheme->parseInfo();

  cp_appearance_validate_subtheme($info, 'branch');
}

/**
 * Submit handler - create the git subtheme entity.
 */
function cp_appearance_manage_git_submit($form, &$form_state) {
  if (empty($form_state['subtheme'])) {
    return;
  }

  $file = $form_state['subtheme'];

  $vsite = vsite_get_vsite();
  $flavors = $vsite->controllers->variable->get('flavors');

  // Parse the info.
  $info = $file->parseInfo();

  // Save the path of the extracted theme for later.
  $flavors[$info['theme name']] = array(
    'path' => $file->path,
    'name' => $info['name'],
  );

  $vsite->controllers->variable->set('flavors', $flavors);

  $form_state['redirect'] = 'cp/appearance';
}


/**
 * Search of the flavors uploaded to the vsite.
 */
function cp_appearance_get_flavors() {
  if (!$vsite = vsite_get_vsite()) {
    return array();
  }
  $flavors = array();

  foreach ($vsite->controllers->variable->get('flavors') as $name => $info) {
    $info_files = glob($info['path'] . '/*.flav');
    $info_file = reset($info_files);

    // Get the information from the info file.
    $file_content = drupal_parse_info_file($info_file);

    $flavors[$name] = $file_content + array(
      'path' => $info['path'],
    );
  }

  return $flavors;
}

/**
 * Implements hook_form_FORM_ID_alter() for os_settings_form.
 */
function cp_appearance_form_os_settings_form_alter(&$form, &$form_state, $form_id) {
  ctools_include('themes', 'os');
  $themes = os_get_themes();
  $theme_options = array();
  foreach ($themes as $name => $theme) {
    $theme_options[$name] = $theme->info['name'];
  }

  $form['cp_appearance_featured_themes'] = array(
    '#type' => 'fieldset',
    '#title' => t('Featured themes'),
    '#weight' => 10,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['cp_appearance_featured_themes']['cp_appearance_featured_display_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Display title'),
    '#weight' => 0,
    '#size' => 20,
    '#default_value' => variable_get('cp_appearance_featured_display_title', t('Featured themes')),
    '#description' => t('The title that displays to users on the Appearance control panel'),
  );
  $form['cp_appearance_featured_themes']['cp_appearance_featured_description'] = array(
    '#type' => 'textarea',
    '#rows' => 2,
    '#title' => t('Description'),
    '#weight' => 1,
    '#default_value' => variable_get('cp_appearance_featured_description', ''),
    '#description' => t('Optional'),
  );
  $form['cp_appearance_featured_themes']['cp_appearance_featured_themes'] = array(
    '#type' => 'checkboxes',
    '#options' => $theme_options,
    '#title' => t('Featured themes'),
    '#weight' => 2,
    '#default_value' => variable_get('cp_appearance_featured_themes', array()),
    '#description' => t('Which themes to display as featured at the top of the Appearance control panel'),
  );
}
