<?php

/**
 * @file
 * This module enables limited HTML to be used in node titles. It strips title
 * markup from RSS feeds to eliminate unsightly markup in feed readers.
 */

/**
 * Implementation of hook_menu()
 */
function html_title_menu() {
  $items['admin/config/content/html_title'] = array(
    'title'            => 'HTML Title settings',
    'description'      => 'Configure HTML tags used in node titles.',
    'access arguments' => array('administer site configuration'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('html_title_admin_settings'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'html_title.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_preprocess_page()
 */
function html_title_preprocess_page(&$vars) {
  if (array_key_exists('node', $vars)) {
    $elements = variable_get('html_title_allowed_elements', array('em', 'sub', 'sup'));
    // Reset title to allow safe HTML
    $vars['title'] = filter_xss($vars['node']->title, $elements);
    // Strip HTML from head title
    $vars['head_title'] = strip_tags($vars['node']->title);
    drupal_set_title($vars['head_title']);
  }
}

/**
 * Implementation of hook_preprocess_node()
 */
function html_title_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'full' || $variables['view_mode'] == 'teaser') {
    $elements = variable_get('html_title_allowed_elements', array('em', 'sub', 'sup'));
    $variables['title'] = filter_xss($variables['elements']['#node']->title, $elements);
  }
}

/**
* Implements hook_node_view().
*/
function html_title_node_view($node, $view_mode) {
  switch ($view_mode) {
    case 'rss':
      $node->title = strip_tags($node->title);
      break;
  }
}

/**
* Implements hook_views_api().
*/
function html_title_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'html_title') .'/views',
  );
}
