<?php
// $Id$


/**
 * @file
 * Code for OS Blog module
 */
include_once 'os_blog.features.inc';

/**
 * Implements hook_os_app_info().
 */
function os_blog_os_app_info() {
  $apps = array();

  $apps['os_blog'] = array(
    'path' => 'blog',
  	'nodetypes' => array(
  	  'blog',
    ),
    'views tabs' => array(
      'os_blog' => array('page'),
    ),
    // Index author in Solr.
    'index author' => TRUE,

    'importers' => array(
      'blog' => array(
        'csv' => 'os_blog_csv',
        'rss' => 'blog_import',
      ),
    ),
    'browse_pages' => array(
      'blog' => array(
        'url' => 'browse/blogs',
        'title' => t('Blog'),
        'display_mode' => 'teaser',
        'menu_item' => 'blog',
      ),
    ),
  );

  return $apps;
}

/**
 * Implements hook_process_hook() for node.
 *
 * Removes the username from $submitted info on blog type nodes.
 */
function os_blog_process_node(&$vars) {
  if ($vars['type'] !== 'blog') {
    return;
  }
  
  if ($vars['view_mode'] == 'title') {
    unset($vars['submitted']);
    return;
  }
  
  // Builds the submitted variable used by default in node templates
  $pubdate = format_date($vars['created'], 'custom', 'F j, Y');
  // Publication date, formatted with time element
  $vars['submitted'] = '<time datetime="' . $vars['datetime'] . '" pubdate="pubdate">' . $pubdate . '</time>';
}

/**
 * Implements hook_vsite_og_node_type_info().
 */
function os_blog_vsite_og_node_type_info() {
  return array(
    'blog' => 'group content',
  );
}

/**
 * Implements hook_os_widget().
 *
 * Exposes blocks as OpenScholar widgets.
 */
function os_blog_os_widget() {
  $items = array();

  // Displays "Archive" list of blog entry nodes by month
  $items['views-os_blog-block'] = array(
    'module' => 'views',
    'delta' => 'os_blog-block',
    'region' => 'sidebar_second',
    'weight' => '-10',
    'info' => 'Blog Archive',
  );

  return $items;
}

//TODO: Remove with os_layout_get is refactored to better handle widget titles
function os_blog_os_widget_alter(&$widget) {
  if ($widget['delta'] == 'os_blog-block') {
    $widget['info'] = 'Blog Archive';
  }
}
