<?php
// $Id$

/**
 * @file
 */

include_once ('os_image_gallery.features.inc');

/**
 * Implements hook_os_app_info().
 */
function os_image_gallery_os_app_info() {
  $apps = array();

  $apps['os_image_gallery'] = array(
    'path' => 'galleries',
  	'nodetypes' => array(
  	  'media_gallery',
    ),
    'views tabs' => array(
      'os_image_gallery' => array('page'),
    ),
    'importers' => array(
      'media_gallery' => array(
        'csv' => 'os_gallery',
      ),
    ),
    'browse_pages' => array(
      'media_gallery' => array(
        'url' => 'browse/gallery',
        'title' => t('Media Galleries'),
        'display_mode' => 'teaser',
        'menu_item' => 'galleries',
      ),
    ),
  );

  return $apps;
}

/**
 * Implements hook_contextual_links_view_alter
 *
 * OS and media_gallery both add contextuals.  Clean that up.
 */
function os_image_gallery_contextual_links_view_alter(&$element, $items) {
  if (isset($element['#contextual_links']['media_gallery'])) {
    unset($element['#links']['media-gallery-edit']);
    unset($element['#links']['file-delete']);
  }
}

/**
 * Implements hook_vsite_og_node_type_info().
 */
function os_image_gallery_vsite_og_node_type_info() {
  return array(
    'media_gallery' => 'group content',
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Removes block option from media_gallery node edit.  OS blocks are managed by layout CP.  This shouldn't be exception.
 */
function os_image_gallery_form_media_gallery_node_form_alter(&$form, &$form_state) {
  $form['block']['#type'] = 'hidden';
}

/**
 * Implements hook_module_implements_alter().
 *
 * Makes sure that os_image_gallery alters the media_gallery form after media_gallery, but before vsite
 */
function os_image_gallery_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['media_gallery'], $implementations['os_image_gallery'])) {
    $os_image_gallery = $implementations['os_image_gallery'];
    unset($implementations['os_image_gallery']);
    $implementations['os_image_gallery'] = $os_image_gallery;

    if (isset($implementations['vsite'])) {
      $vsite = $implementations['vsite'];
      unset($implementations['vsite']);
      $implementations['vsite'] = $vsite;
    }
  }
}

/**
 * Implements hook_node_view().
 */
function os_image_gallery_node_view($node, $view_mode) {
  if ($node->type !== 'media_gallery') {
    return;
  }

  // Invokes media_gallery_view(), since this feature "owns" the media_gallery
  // node type.
  media_gallery_view($node, $view_mode);

  //Update link title so users know they can upload more than just images
  if (isset($node->content['add_media_link']['select']) && $node->content['add_media_link']['select']['#title'] == t('Add New Image')) {
    $node->content['add_media_link']['select']['#title'] = t('Add New Media');
  }


  // Attaches custom CSS to this node view page.
  $node->content['os_image_gallery'] = array(
    '#attached' => array(
      'css' => array(
        'type' => 'file',
        'data' => drupal_get_path('module', 'os_image_gallery') . '/os_image_gallery.css',
      ),
    ),
  );

  // Gets the fids of images on this page
  if (isset($node->media_gallery_file[$node->language]) && count($node->media_gallery_file[$node->language])) {
    $keep_fids = array();  
    foreach ($node->media_gallery_file as $lang) {
      foreach ($lang as $media) {
        $keep_fids[] = $media['fid'];
      }
    }
    

    // Removes the rest
    foreach ($node->content['media_gallery_file'] as $delta => $media) {
      if (is_numeric($delta) && !in_array($media['#file']->fid, $keep_fids)) {
        unset($node->content['media_gallery_file'][$delta]);
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function os_image_gallery_form_alter(&$form, &$form_state, $form_id) {
  if (@is_array($form_state['build_info']['args'][0]) && @$form_state['build_info']['args'][0]['id'] == 'media_gallery') {
    $field_info = field_info_instance('node', 'media_gallery_file', 'media_gallery');
    $max = parse_size($field_info['settings']['max_filesize']);
    $form['upload']['#upload_validators']['file_validate_size'][0] = min($max, $form['upload']['#upload_validators']['file_validate_size']);
    
    $form['upload']['#upload_validators']['os_image_gallery_upload_filesize'] = array();
  }
}

/**
 * @function os_image_gallery_upload_filesize
 *
 * #upload_validator ensures max filesize used in media gallery uploads
 */
function os_image_gallery_upload_filesize($file) {
  $errors = array();
  $info = field_info_instance('node', 'media_gallery_file', 'media_gallery');
  
  $max = parse_size($info['settings']['max_filesize']);
  if (is_numeric($max) && 0 < $max && $max < $file->filesize) {
    $errors[] = t('The file size limit for media gallery files is !max', array('!max' => $info['settings']['max_filesize']));  
  }
  
  return $errors;
}

/**
 * Implements hook_file_delete
 *
 * When an image is deleted, remove it from media_gallery nodes first.
 */
function os_image_gallery_file_delete($file) {
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->fieldCondition('media_gallery_file', 'fid', $file->fid, '=');
  $result = $query->execute();

  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    $nodes = entity_load('node', $nids);
    foreach ($nodes as $node) {
      media_gallery_remove_item_from_gallery($node, $file);
    }
  }
}

/**
 * Media item thumbnails of flash videos should be images.  Full display should show flash.
 */
function os_image_gallery_theme_registry_alter(&$registry){
  array_unshift($registry['media_gallery_media_item_thumbnail']['preprocess functions'], 'os_image_gallery_preprocess_media_item_thumbnail'); 
}

/**
 * Implements hook_preprocess_media_item_thumbnail
 * 
 * Sets a flag that we're viewing a thumbnail.  Further down the line this will change
 * What theme function renders this file field.
 * 
 * Also change the cache key so thumbnail and lightbox view don't get html from same cache
 */
function os_image_gallery_preprocess_media_item_thumbnail(&$vars) {
  if ($vars['element']['#bundle'] == 'video') {
    $vars['element']['file']['#display'] = 'thumbnail';
    $vars['element']['file']['#cache']['keys'][] = 'os_image_gallery_thumbnail_' . $vars['element']['#file']->fid;
  }
}

/**
 * Impelements hook_element_info_alter
 *
 * Gives oembed a final pre_render function.  oembed_element_info has already
 * provided a retheme pre_render function that overrides any theme I may have set.
 * This overrides that.
 */
function os_image_gallery_element_info_alter(&$type) {
  if (isset($type['oembed'])) {
    $type['oembed']['#pre_render'][] = 'os_image_gallery_oembed_pre_render_retheme';
  }
}

/**
 * @function os_image_gallery_oembed_pre_render_retheme
 * 
 * oembed's pre_render function sets the theme.  this undoes that change so we can use our own themeing function to get 
 * flash to display in something that isn't an iframe.
 */
function os_image_gallery_oembed_pre_render_retheme(&$element) {
  if (isset($element['#display']) && ($element['#display'] == 'thumbnail')) {
    $element['#theme'] = 'os_image_gallery_file_field_inline';
    //array_unshift($element['#cache']['keys'], 'image_gallery_thumbnail'); //too late
  }
  
  return $element;
}

/**
 * Implements hook_theme
 */
function os_image_gallery_theme($existing, $type, $theme, $path) {
  return array('os_image_gallery_file_field_inline' => array(
    'function' => 'theme_os_image_gallery_file_field_inline',
    'render element' => 'element',
  ));
}

/**
 * Implements theme_MODULE_hook
 * 
 * Theme function for thumbnails of flash objects.  
 */
function theme_os_image_gallery_file_field_inline($variables) {
  $img = $variables['element']['#embed']->thumbnail_url;
  $clear = drupal_get_path('module', 'os_image_gallery') . '/trans.gif';
  
  $attributes = array('style' => "background: url('$img') no-repeat center; background-size: auto 100%;");
  $indicator = '<span class="video-indicator"> </span>';
  return theme('image', array('path'=>$clear, 'attributes' => $attributes)) . $indicator;
}

/**
 * Implements hook_preprocess_media_gallery_meta.
 *
 * Replaces media_title with the filename
 */
function os_image_gallery_preprocess_media_gallery_meta(&$vars) {
  $frags = explode('/', $vars['link_path']);
  if ($file = file_load($frags[3])) {
    $vars['title'] = $file->filename;
  }
}
