<?php
// $Id$


/**
 * @file
 * rbuild.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function rbuild_field_default_fields() {
  $fields = array();

  // Exported field: 'node-software_project-field_rbuild_short_name'
  $fields['node-software_project-field_rbuild_short_name'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_rbuild_short_name',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'software_project',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Note: Verify this unique rBuild short name corresponds to the Repository URL value above',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 6,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_rbuild_short_name',
      'label' => 'rBuild Short Name',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '4',
      ),
    ),
  );

  // Exported field: 'node-software_project-field_software_repo'
  $fields['node-software_project-field_software_repo'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_software_repo',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'software_project',
      'default_value' => 'http://r.iq.harvard.edu/src/contrib',
      'deleted' => '0',
      'description' => 'Example: http://r.iq.harvard.edu/src/contrib',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '4',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '3',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_software_repo',
      'label' => 'Repository URL',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '3',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Description');
  t('Documentation');
  t('Example: http://r.iq.harvard.edu/src/PACKAGE.CookingRecipes');
  t('Note: Verify this unique rBuild short name corresponds to the Repository URL value above');
  t('Notes');
  t('Package');
  t('Packaging Method');
  t('Recommended');
  t('Repository URL');
  t('Software Project');
  t('The recommended releases will be displayed on the project page. The latest recommended release per major version will be offered for update status.');
  t('Version');
  t('rBuild Short Name');

  return $fields;
}

