<?php
include_once('iqss_projects_front.features.inc');

/**
 * implementation of hook_context_default_contexts_alter
 */
function iqss_projects_front_context_default_contexts_alter(&$contexts){
  // add some extra blocks/boxes to the 'sitewide_front'
  if (isset($contexts['os_sitewide_front'])) {
    $fp_blocks = &$contexts['os_sitewide_front']->reactions['block']['blocks'];

    $fp_blocks['boxes-iqss_projects_fp_infoblock'] = array(
        'module' => 'boxes',
        'delta' => 'iqss_projects_fp_infoblock',
        'weight' => -100,
        'region' => 'content_top',
    );

    $fp_blocks['boxes-iqss_projects_fp_logoblock'] = array(
        'module' => 'boxes',
        'delta' => 'iqss_projects_fp_logoblock',
        'weight' => -100,
        'region' => 'header_first',
    );

    $fp_blocks['boxes-iqss_projects_fp_features'] = array(
        'module' => 'boxes',
        'delta' => 'iqss_projects_fp_features',
        'weight' => 10,
        'region' => 'content_first',
    );

    $fp_blocks['boxes-iqss_projects_fp_stats'] = array(
        'module' => 'os_stats',
        'delta' => 'os_stats',
        'weight' => 10,
        'region' => 'footer',
    );

    $fp_blocks['boxes-iqss_projects_fp_navblock'] = array(
        'module' => 'boxes',
        'delta' => 'iqss_projects_fp_navblock',
        'weight' => -100,
        'region' => 'header_second',
    );

    if(isset($fp_blocks['vsite_register-get_your_site_block'])){
      // Unset this block reaction as we're not using it on the projects site.
      // We are using the logic of this box in another box (infoblock).
      unset($fp_blocks['vsite_register-get_your_site_block']);
    }

    $fp_blocks['views-os_websites-block'] = array(
      'module' => 'views',
      'delta' => 'os_websites-block',
      'region' => 'content_bottom',
      'weight' => '-9',
    );
  }

  // Add extra boxes to the os_sitewide context.
  if (isset($contexts['os_sitewide'])) {
    $fp_blocks = &$contexts['os_sitewide']->reactions['block']['blocks'];

    // Add the projects logo.
    $fp_blocks['boxes-iqss_projects_fp_logoblock'] = array(
      'module' => 'boxes',
      'delta' => 'iqss_projects_fp_logoblock',
      'region' => 'header_first',
      'weight' => '-10',
    );

    // Add the projects nav links.
    $fp_blocks['boxes-iqss_projects_fp_navblock'] = array(
      'module' => 'boxes',
      'delta' => 'iqss_projects_fp_navblock',
      'region' => 'header_second',
      'weight' => '-10',
    );
  }
}

/**
 * Implements hook_os_widget_alter().
 */
function iqss_projects_front_os_widget_alter(&$widget) {
  //Keep the default box instances that this module provides from getting used sitewide
  if($widget['module'] == 'boxes' && function_exists('iqss_projects_front_default_box')){
    static $fp_boxes;
    //Front Page Boxes
    if(!isset($fp_boxes)) $fp_boxes =  iqss_projects_front_default_box();

    if(isset($fp_boxes[$widget['delta']])){
      $widget['hidden'] = true;
    }
  }
}

/**
 * Implement hook_strongarm
 * Strongarm hook for configuration variables
 * for the os_stats block
 */
function iqss_projects_front_strongarm() {
	$export = array();

	$strongarm = new stdClass();
  	$strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  	$strongarm->api_version = 1;
  	$strongarm->name = 'os_stats_cache_expiration';
  	$strongarm->value = (int)3600*24;
  	$export['os_stats_cache_expiration'] = $strongarm;

	$strongarm = new stdClass();
  	$strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  	$strongarm->api_version = 1;
  	$strongarm->name = 'os_stats_enabled';
  	$strongarm->value = array(
  		'filesize' => 0,
  		'users' => 0,
  		'websites' => 1,
  		'posts' => 1,
  		'publications' => 0,
  		'files' => 1,
  	);
  	$export['os_stats_enabled'] = $strongarm;

  	return $export;
}

/**
 * Implements hook_preprocess_page().
 * Add the jcarousel call into the preprocess page for the projects front page
 */
function iqss_projects_front_preprocess_page(&$variables){
  // Add in the jcarousel call.
  // Make sure we're on the front page only and the jcarousel module exists.
  if(module_exists('jcarousel')) {
    if(drupal_is_front_page() == TRUE) {
      jcarousel_add('os-jcarousel-skin-os_front ul',array('skin'=>'os_front'),TRUE);
    }
  }
}

/**
 * Implements hook_jcarousel_skin_info().
 * Allows us to use our own custom CSS file for the carousel skin.
 */
function iqss_projects_front_jcarousel_skin_info() {
  $skins = array();
  $skins['os_front'] = array(
    'title' => t('OpenScholar Projects Front Page'),
    'file' => 'carousel.css',
  );
  return $skins;
}
