<?php
include_once('iqss_scholars_front.features.inc');

/**
 * implementation of hook_context_default_contexts_alter
 */
function iqss_scholars_front_context_default_contexts_alter(&$contexts){
  // add some extra blocks/boxes to the 'sitewide_front'
  if (isset($contexts['os_sitewide_front'])) {
    $fp_blocks = &$contexts['os_sitewide_front']->reactions['block']['blocks'];

    $fp_blocks['boxes-iqss_scholars_fp_headertext'] = array(
        'module' => 'boxes',
        'delta' => 'iqss_scholars_fp_headertext',
        'weight' => 10,
        'region' => 'header_second',
    );

    $fp_blocks['boxes-iqss_scholars_fp_infoblock'] = array(
        'module' => 'boxes',
        'delta' => 'iqss_scholars_fp_infoblock',
        'weight' => 10,
        'region' => 'content_top',
    );

    $fp_blocks['boxes-iqss_scholars_fp_logoblock'] = array(
        'module' => 'boxes',
        'delta' => 'iqss_scholars_fp_logoblock',
        'weight' => 10,
        'region' => 'header_first',
    );

    $fp_blocks['boxes-iqss_scholars_fp_learnmore'] = array(
        'module' => 'boxes',
        'delta' => 'iqss_scholars_fp_learnmore',
        'weight' => 100,
        'region' => 'sidebar_second',
    );

    $fp_blocks['boxes-iqss_scholars_fp_stats'] = array(
        'module' => 'os_stats',
        'delta' => 'os_stats',
        'weight' => 10,
        'region' => 'footer',
    );

    $fp_blocks['boxes-iqss_scholars_learnmore_toggle'] = array(
      'module' => 'boxes',
      'delta' => 'iqss_scholars_learnmore_toggle',
      'weight' => -40,
      'region' => 'footer',
    );

    $fp_blocks['views-os_websites-block'] = array(
      'module' => 'views',
      'delta' => 'os_websites-block',
      'region' => 'content_bottom',
      'weight' => '-9',
    );
    $fp_blocks['views-os_activity-block_1'] = array(
      'module' => 'views',
      'delta' => 'os_activity-block_1',
      'region' => 'footer',
      'weight' => '-30',
    );

  }

  // Add extra boxes to the os_sitewide context
  if (isset($contexts['os_sitewide'])) {
    $fp_blocks = &$contexts['os_sitewide']->reactions['block']['blocks'];

    $fp_blocks['boxes-iqss_scholars_fixed_header'] = array(
      'module' => 'boxes',
      'delta' => 'iqss_scholars_fixed_header',
      'region' => 'header_top',
      'weight' => '-10',
    );
  }
}

/**
 * Implements hook_os_widget_alter().
 */
function iqss_scholars_front_os_widget_alter(&$widget) {
  //Keep the default box instances that this module provides from getting used sitewide
  if($widget['module'] == 'boxes' && function_exists('iqss_scholars_front_default_box')){
    static $fp_boxes;
    //Front Page Boxes
    if(!isset($fp_boxes)) $fp_boxes =  iqss_scholars_front_default_box();

		if(isset($fp_boxes[$widget['delta']])){
		  $widget['hidden'] = true;
		}
  }
}

/**
 * Implement hook_strongarm
 * Strongarm hook for configuration variables
 * for the os_stats block
 */
function iqss_scholars_front_strongarm() {
	$export = array();

	$strongarm = new stdClass();
  	$strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  	$strongarm->api_version = 1;
  	$strongarm->name = 'os_stats_cache_expiration';
  	$strongarm->value = (int)3600*24;
  	$export['os_stats_cache_expiration'] = $strongarm;

	$strongarm = new stdClass();
  	$strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  	$strongarm->api_version = 1;
  	$strongarm->name = 'os_stats_enabled';
  	$strongarm->value = array(
  		'filesize' => 0,
  		'users' => 0,
  		'websites' => 1,
  		'posts' => 1,
  		'publications' => 1,
  		'files' => 1,
  	);
  	$export['os_stats_enabled'] = $strongarm;

  	return $export;
}

/**
 * Implements hook_image_default_styles().
 */
function iqss_scholars_front_image_default_styles() {
  $styles = array();

  // Exported image style: iqss_scholars_front_websites_180_x_140.
  $styles['iqss_scholars_front_websites_180_x_140'] = array(
    'name' => 'iqss_scholars_front_websites_180_x_140',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '180',
          'height' => '140',
        ),
        'weight' => '1',
      ),
    ),
  );

  return $styles;
}